import { Wine } from "./types";

export const WINE_CATALOG: Wine[] = [
  {
    id: "w001",
    name: "Barolo Serralunga d'Alba",
    producer: "Fontanafredda",
    vintage: 2018,
    type: "Rot",
    region: "Piemont",
    country: "Italien",
    grapes: ["Nebbiolo"],
    alcohol: 14.5,
    drinkFrom: 2022,
    drinkPeak: 2028,
    drinkUntil: 2035,
    pairing: ["Rind", "Wild", "Hartkäse", "Trüffel"],
    referencePrice: 42,
    description: "Kraftvoller Barolo mit Noten von Kirschen, Tabak und Rosen. Elegant und langlebig.",
    barcode: "8001234567890",
  },
  {
    id: "w002",
    name: "Château Margaux",
    producer: "Château Margaux",
    vintage: 2015,
    type: "Rot",
    region: "Médoc / Margaux",
    country: "Frankreich",
    grapes: ["Cabernet Sauvignon", "Merlot", "Petit Verdot"],
    alcohol: 13.5,
    drinkFrom: 2020,
    drinkPeak: 2035,
    drinkUntil: 2050,
    pairing: ["Rind", "Lamm", "Wildgeflügel"],
    referencePrice: 890,
    description: "Premier Grand Cru Classé. Samtweich, mit Cassis, Zedernholz und Veilchen.",
  },
  {
    id: "w003",
    name: "Riesling Spätlese Ürziger Würzgarten",
    producer: "Dr. Loosen",
    vintage: 2021,
    type: "Weiss",
    region: "Mosel",
    country: "Deutschland",
    grapes: ["Riesling"],
    alcohol: 8.0,
    drinkFrom: 2023,
    drinkPeak: 2030,
    drinkUntil: 2040,
    pairing: ["Fisch", "Meeresfrüchte", "Asiagerichte", "Geflügel"],
    referencePrice: 28,
    description: "Klassische Mosel-Eleganz. Pfirsich, Aprikose, mineralische Schiefernote.",
    barcode: "4003001234567",
  },
  {
    id: "w004",
    name: "Brunello di Montalcino",
    producer: "Biondi-Santi",
    vintage: 2016,
    type: "Rot",
    region: "Toskana",
    country: "Italien",
    grapes: ["Sangiovese Grosso"],
    alcohol: 14.0,
    drinkFrom: 2024,
    drinkPeak: 2033,
    drinkUntil: 2045,
    pairing: ["Rind", "Wild", "Schmorgerichte", "Hartkäse"],
    referencePrice: 145,
    description: "Eleganter Brunello mit reifer Kirsche, Leder und Tabak. Langer Abgang.",
  },
  {
    id: "w005",
    name: "Grüner Veltliner Smaragd Wachau",
    producer: "F.X. Pichler",
    vintage: 2022,
    type: "Weiss",
    region: "Wachau",
    country: "Österreich",
    grapes: ["Grüner Veltliner"],
    alcohol: 14.0,
    drinkFrom: 2023,
    drinkPeak: 2028,
    drinkUntil: 2034,
    pairing: ["Fisch", "Gemüse", "Geflügel", "Weichkäse"],
    referencePrice: 55,
    description: "Kraftvoller Smaragd, weisser Pfeffer, Steinobst, mineralisch und lang.",
    barcode: "9001234567890",
  },
  {
    id: "w006",
    name: "Champagne Blanc de Blancs",
    producer: "Billecart-Salmon",
    vintage: 2014,
    type: "Schaumwein",
    region: "Champagne",
    country: "Frankreich",
    grapes: ["Chardonnay"],
    alcohol: 12.5,
    drinkFrom: 2020,
    drinkPeak: 2027,
    drinkUntil: 2032,
    pairing: ["Austern", "Kaviar", "Fisch", "Sushi"],
    referencePrice: 85,
    description: "Eleganter Blanc de Blancs, feine Perlage, Brioche, Zitrus und Kreide.",
  },
  {
    id: "w007",
    name: "Pinot Noir Village",
    producer: "Domaine de la Romanée-Conti",
    vintage: 2019,
    type: "Rot",
    region: "Burgund",
    country: "Frankreich",
    grapes: ["Pinot Noir"],
    alcohol: 13.0,
    drinkFrom: 2023,
    drinkPeak: 2030,
    drinkUntil: 2038,
    pairing: ["Wild", "Pilze", "Ente", "Lamm"],
    referencePrice: 340,
    description: "Seidiger Burgunder mit Kirsche, Veilchen und erdiger Tiefe.",
  },
  {
    id: "w008",
    name: "Sancerre Les Monts Damnés",
    producer: "Henri Bourgeois",
    vintage: 2022,
    type: "Weiss",
    region: "Loire",
    country: "Frankreich",
    grapes: ["Sauvignon Blanc"],
    alcohol: 13.0,
    drinkFrom: 2023,
    drinkPeak: 2026,
    drinkUntil: 2029,
    pairing: ["Ziegenkäse", "Fisch", "Salate", "Spargel"],
    referencePrice: 32,
    description: "Frischer Sauvignon mit Grapefruit, grüner Paprika und Kieselstein-Mineralik.",
    barcode: "3012345678901",
  },
  {
    id: "w009",
    name: "Rioja Gran Reserva",
    producer: "Marqués de Riscal",
    vintage: 2016,
    type: "Rot",
    region: "Rioja",
    country: "Spanien",
    grapes: ["Tempranillo", "Graciano", "Mazuelo"],
    alcohol: 14.0,
    drinkFrom: 2021,
    drinkPeak: 2028,
    drinkUntil: 2036,
    pairing: ["Lamm", "Rind", "Schinken", "Chorizo"],
    referencePrice: 38,
    description: "Klassische Rioja-Reife, Vanille, Kokos, dunkle Früchte.",
    barcode: "8410298012345",
  },
  {
    id: "w010",
    name: "Primitivo di Manduria",
    producer: "Gianfranco Fino",
    vintage: 2020,
    type: "Rot",
    region: "Apulien",
    country: "Italien",
    grapes: ["Primitivo"],
    alcohol: 16.0,
    drinkFrom: 2022,
    drinkPeak: 2027,
    drinkUntil: 2032,
    pairing: ["Barbecue", "Rind", "Pasta", "Würste"],
    referencePrice: 48,
    description: "Konzentriert und warm, Pflaume, Schokolade, Gewürze.",
    barcode: "8001234512345",
  },
  {
    id: "w011",
    name: "Chablis Premier Cru Montée de Tonnerre",
    producer: "William Fèvre",
    vintage: 2021,
    type: "Weiss",
    region: "Burgund / Chablis",
    country: "Frankreich",
    grapes: ["Chardonnay"],
    alcohol: 13.0,
    drinkFrom: 2023,
    drinkPeak: 2029,
    drinkUntil: 2034,
    pairing: ["Austern", "Krustentiere", "Fisch", "Sashimi"],
    referencePrice: 45,
    description: "Stahlige Mineralik, Zitrus, Kreide und Jodsalz. Pur und präzise.",
  },
  {
    id: "w012",
    name: "Amarone della Valpolicella Classico",
    producer: "Allegrini",
    vintage: 2017,
    type: "Rot",
    region: "Venetien",
    country: "Italien",
    grapes: ["Corvina", "Rondinella", "Molinara"],
    alcohol: 15.5,
    drinkFrom: 2022,
    drinkPeak: 2030,
    drinkUntil: 2040,
    pairing: ["Schmorgerichte", "Hartkäse", "Wildschein", "Schokolade"],
    referencePrice: 72,
    description: "Mächtig und komplex, Rosinen, Kirschen, Bitterschokolade, Balsam.",
    barcode: "8023209012345",
  },
  {
    id: "w013",
    name: "Gewürztraminer Vendanges Tardives",
    producer: "Hugel",
    vintage: 2017,
    type: "Dessertwein",
    region: "Elsass",
    country: "Frankreich",
    grapes: ["Gewürztraminer"],
    alcohol: 13.5,
    drinkFrom: 2021,
    drinkPeak: 2030,
    drinkUntil: 2040,
    pairing: ["Foie Gras", "Roquefort", "Desserts", "Obstkuchen"],
    referencePrice: 68,
    description: "Opulent und würzig, Rose, Lychee, Honig und Mango.",
  },
  {
    id: "w014",
    name: "Prosecco Valdobbiadene Superiore DOCG",
    producer: "Nino Franco",
    vintage: 2023,
    type: "Schaumwein",
    region: "Venetien",
    country: "Italien",
    grapes: ["Glera"],
    alcohol: 11.5,
    drinkFrom: 2023,
    drinkPeak: 2025,
    drinkUntil: 2026,
    pairing: ["Aperitif", "Meeresfrüchte", "Risotto", "Prosciutto"],
    referencePrice: 18,
    description: "Lebendig und frisch, Birne, Apfel, weisse Blüten.",
    barcode: "8004823012345",
  },
  {
    id: "w015",
    name: "Malbec Alto Valle",
    producer: "Achaval Ferrer",
    vintage: 2021,
    type: "Rot",
    region: "Mendoza",
    country: "Argentinien",
    grapes: ["Malbec"],
    alcohol: 14.5,
    drinkFrom: 2023,
    drinkPeak: 2028,
    drinkUntil: 2034,
    pairing: ["Rind", "Barbecue", "Empanadas", "Hartkäse"],
    referencePrice: 34,
    description: "Dunkle Pflaumen, Veilchen, Schokolade und weiche Tannine.",
    barcode: "7790012345678",
  },
  {
    id: "w016",
    name: "Albariño Rías Baixas",
    producer: "Pazo de Señoráns",
    vintage: 2022,
    type: "Weiss",
    region: "Galicien",
    country: "Spanien",
    grapes: ["Albariño"],
    alcohol: 13.0,
    drinkFrom: 2022,
    drinkPeak: 2025,
    drinkUntil: 2028,
    pairing: ["Seafood", "Fisch", "Gambas", "Pulpo"],
    referencePrice: 22,
    description: "Spritziger Atlantik-Weisswein, Pfirsich, Grapefruit und Salzmandeln.",
    barcode: "8410512345678",
  },
  {
    id: "w017",
    name: "Syrah Crozes-Hermitage",
    producer: "Chapoutier",
    vintage: 2020,
    type: "Rot",
    region: "Rhône",
    country: "Frankreich",
    grapes: ["Syrah"],
    alcohol: 13.5,
    drinkFrom: 2023,
    drinkPeak: 2029,
    drinkUntil: 2035,
    pairing: ["Wild", "Rind", "Oliventapenade", "Grillgerichte"],
    referencePrice: 26,
    description: "Schwarze Beeren, Oliven, Pfeffer und etwas Raucharome.",
    barcode: "3012312345678",
  },
  {
    id: "w018",
    name: "Zinfandel Sonoma Valley",
    producer: "Ridge Vineyards",
    vintage: 2020,
    type: "Rot",
    region: "Sonoma Valley",
    country: "USA",
    grapes: ["Zinfandel"],
    alcohol: 15.0,
    drinkFrom: 2022,
    drinkPeak: 2027,
    drinkUntil: 2032,
    pairing: ["Barbecue", "Pizza", "Burger", "Chorizo"],
    referencePrice: 38,
    description: "Charaktervoller Zinfandel, Brombeere, Gewürze, Vanille.",
    barcode: "0012345678901",
  },
  {
    id: "w019",
    name: "Pouilly-Fumé",
    producer: "Didier Dagueneau",
    vintage: 2021,
    type: "Weiss",
    region: "Loire",
    country: "Frankreich",
    grapes: ["Sauvignon Blanc"],
    alcohol: 13.5,
    drinkFrom: 2022,
    drinkPeak: 2028,
    drinkUntil: 2033,
    pairing: ["Ziegenkäse", "Spargel", "Meeresfrüchte", "Sushi"],
    referencePrice: 95,
    description: "Legendär – Feuerstein, Grapefruit, Holunder. Unvergleichlich präzise.",
  },
  {
    id: "w020",
    name: "Châteauneuf-du-Pape",
    producer: "Château Rayas",
    vintage: 2018,
    type: "Rot",
    region: "Rhône",
    country: "Frankreich",
    grapes: ["Grenache", "Syrah", "Mourvèdre"],
    alcohol: 14.0,
    drinkFrom: 2023,
    drinkPeak: 2032,
    drinkUntil: 2042,
    pairing: ["Lamm", "Wild", "Paella", "Käse"],
    referencePrice: 280,
    description: "Komplex und elegant, rote Beeren, Kräuter, Garrigue.",
  },
];

export function searchWines(query: string): Wine[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return WINE_CATALOG.filter(
    (w) =>
      w.name.toLowerCase().includes(q) ||
      w.producer.toLowerCase().includes(q) ||
      w.region.toLowerCase().includes(q) ||
      w.country.toLowerCase().includes(q) ||
      w.grapes.some((g) => g.toLowerCase().includes(q)) ||
      String(w.vintage).includes(q)
  ).slice(0, 10);
}

export function findByBarcode(barcode: string): Wine | undefined {
  return WINE_CATALOG.find((w) => w.barcode === barcode);
}

export function getWineById(id: string): Wine | undefined {
  return WINE_CATALOG.find((w) => w.id === id);
}

export function getDrinkingStatus(wine: Wine): "peak" | "ready" | "soon" | "wait" | "overdue" {
  const year = new Date().getFullYear();
  if (year > wine.drinkUntil) return "overdue";
  if (year >= wine.drinkPeak && year <= wine.drinkUntil) return "peak";
  if (year >= wine.drinkFrom && year < wine.drinkPeak) return "ready";
  if (year === wine.drinkFrom - 1) return "soon";
  return "wait";
}
